name: web_fake_n_hate

services:
    flask:
        build:
            context: .
        volumes:
            - ./flask_app:/web_fakehate:z
        expose:
            - "5000"
        container_name: flask_app
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        container_name: nginx_proxy
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:z
        depends_on:
            - flask